name: Pipeline Example
run-name: example-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  IMAGE_NAME: laba-project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: '8.4'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test --no-build-cache
      - name: Build Image
        run: | 
          echo "Building docker image"
          docker build -t \${{env.IMAGE_NAME}}:latest .
          docker build -t \${{ env.IMAGE_NAME }}:\${{ github.sha }} .
      - name: Test Docker Container
        run: |
          echo "Testing docker container"
          docker run --rm \${{ env.IMAGE_NAME }}:latest
      - name: List Docker images
        run: |
          echo "List image"
          docker images | grep \${{ env.IMAGE_NAME }}