name: Pipeline Example
run-name: example-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: '8.4'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew build --no-build-cache